version: '3'
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  postgres:
    image: "postgres:latest"
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "links"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - postgres
  consumer1:
    build: .
    command: node consumer.js Consumer1
    depends_on:
      - rabbitmq

  consumer2:
    build: .
    command: node consumer.js Consumer2
    depends_on:
      - rabbitmq